// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQf78avIiRRoCrxiL5RNayxcHvpSpykew',
    appId: '1:95963291805:web:ad38e17d37904e827fb474',
    messagingSenderId: '95963291805',
    projectId: 'ascend-app-6e800',
    authDomain: 'ascend-app-6e800.firebaseapp.com',
    databaseURL: 'https://ascend-app-6e800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ascend-app-6e800.appspot.com',
    measurementId: 'G-Z1LPREGG87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaSKYT7jbfLhjDJztJYXss1lDeYXql08U',
    appId: '1:95963291805:android:7fa73b23838d3a657fb474',
    messagingSenderId: '95963291805',
    projectId: 'ascend-app-6e800',
    databaseURL: 'https://ascend-app-6e800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ascend-app-6e800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdCcoBsWJb5q29S-iznphPDDkVySNQldU',
    appId: '1:95963291805:ios:0d9a6f103a7bd19a7fb474',
    messagingSenderId: '95963291805',
    projectId: 'ascend-app-6e800',
    databaseURL: 'https://ascend-app-6e800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ascend-app-6e800.appspot.com',
    iosBundleId: 'com.example.ascendFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdCcoBsWJb5q29S-iznphPDDkVySNQldU',
    appId: '1:95963291805:ios:d0afa4c02c4c68fe7fb474',
    messagingSenderId: '95963291805',
    projectId: 'ascend-app-6e800',
    databaseURL: 'https://ascend-app-6e800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ascend-app-6e800.appspot.com',
    iosBundleId: 'com.example.ascendFyp.RunnerTests',
  );
}
